# Generated by Django 5.2.6 on 2025-11-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kilograms', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MushroomBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_name', models.CharField(max_length=100)),
                ('bag_type', models.CharField(choices=[('oyster', 'Oyster Mushroom'), ('shiitake', 'Shiitake'), ('button', 'Button Mushroom'), ('portobello', 'Portobello'), ('other', 'Other')], max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('incubating', 'Incubating'), ('fruiting', 'Fruiting'), ('harvested', 'Harvested'), ('discarded', 'Discarded')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
