# Generated by Django 5.2.6 on 2025-11-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mushroombag',
            name='firebase_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mushroombag',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
